version: '3.3' 
services:
  web:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    container_name: blue-shop-container
    volumes:
      - ../:/var/www/html/
    ports:
      - 8202:80
